import { v } from "convex/values";
import { mutation, query } from "./_generated/server";

export const createQuiz = mutation({
    args: {
        storyId: v.id("stories"),
        // In a real scenario, questions might be generated by AI and passed here,
        // or generated inside this mutation.
        questions: v.array(
            v.object({
                id: v.string(),
                questionType: v.string(),
                prompt: v.string(),
                options: v.array(
                    v.object({
                        id: v.string(),
                        label: v.string(),
                        imageUrl: v.optional(v.string()),
                    })
                ),
                correctOptionId: v.string(),
            })
        ),
    },
    handler: async (ctx, args) => {
        const quizId = await ctx.db.insert("quizzes", {
            storyId: args.storyId,
            questions: args.questions,
            createdAt: Date.now(),
        });
        return quizId;
    },
});

export const getQuizForStory = query({
    args: { storyId: v.id("stories") },
    handler: async (ctx, args) => {
        return await ctx.db
            .query("quizzes")
            .withIndex("by_story", (q) => q.eq("storyId", args.storyId))
            .unique();
    },
});

export const submitQuizResult = mutation({
    args: {
        childId: v.id("children"),
        storyId: v.id("stories"),
        quizId: v.id("quizzes"),
        score: v.number(),
        maxScore: v.number(),
    },
    handler: async (ctx, args) => {
        await ctx.db.insert("quizResults", {
            childId: args.childId,
            storyId: args.storyId,
            quizId: args.quizId,
            score: args.score,
            maxScore: args.maxScore,
            completedAt: Date.now(),
        });
    },
});
